version: "3.9"

services:

  api:
    container_name: api
    build: .
    environment:
      PG_CONNECTION_STRING: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_DB}:${POSTGRES_PORT}"
      PORT: 
    ports:
      - "3000:3000"

  db:
    container_name: ${POSTGRES_DB}
    image: postgres
    restart: always
    environment:
      POSTGRESS_PASSWORD: 
      POSTGRESS_USER: 
      POSTGRESS_DB: 
      POSTGRES_HOST_AUTH_METHOD: trust