version: "3.9"

services:

  api:
    container_name: api
    build: ./api
    environment:
      PG_CONNECTION_STRING: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}"
      PORT: 
    ports:
      - "3000:3000"

  db:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_PASSWORD: 
      POSTGRES_USER: 
      POSTGRES_DB: 
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}