version: "3.9"

services:
  api:
    build: ./api
    environment:
      PG_CONNECTION_STRING: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}"
      PORT:
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  watchtower:
    image: containrrr/watchtower
    command: "--interval 60 --cleanup"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
