name: Deploy

on:
  push:
    branches: [ main ]

env:
  POSTGRES_PASSWORD: test
  POSTGRES_USER: test
  POSTGRES_DB: database
  POSTGRES_PORT: 5432
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: docker-compose build
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish
        run: docker-compose push
